config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'sessions'}

  scope 'admin', :module => 'back', :as => 'back' do
    root to: "activites#index"

    resources :activites do
      member do
        get  'publish_status/:publish', :action => 'publish_status', :as => 'publish_status'
        get  'previsu', :action => 'previsu', :as => 'previsu'
      end
    end
    post 'activites/update/all', to: 'activites#update_all', :as => 'activite_update_all'

    resources :sousactivites do
      member do
        get  'publish_status/:publish', :action => 'publish_status', :as => 'publish_status'
        get  'previsu', :action => 'previsu', :as => 'previsu'
      end

      post 'sousactivite_images/update_row_order', to: 'sousactivite_images#update_row_order', as: 'update_row_order', on: :collection
      resources :sousactivite_images
    end

    resources :news do
      member do
        get  'publish_status/:publish', :action => 'publish_status', :as => 'publish_status'
        get  'previsu', :action => 'previsu', :as => 'previsu'
      end
    end
    post 'news/update/all', to: 'news#update_all', :as => 'news_update_all'

  end

  scope :module => 'front', :as => 'front' do
    root :to => 'indexs#index'

    resources :contact_forms, :only => [:create]

  end

 end

app/models/sousactivite_image.rb
class SousactiviteImage < ActiveRecord::Base
	include RankedModel
	ranks :row_order	
end

app/controllers/back/activites_controller.rb
# -*- coding: utf-8 -*-

class Back::ActivitesController < BackController
  include Tools

  before_action :set_activite, only: [:show, :edit, :update, :destroy, :publish_status, :previsu]

  def index
    @activites = Activite.order("activites.title ASC").filter(get_params).page(params[:page]).per(5)
    session[:tabs] = ""
  end

  def show
  end

  def new
    @activite = Activite.new
  end

  def edit
  end

  def previsu
  end

  def create
    @activite = Activite.new(activite_params)

    respond_to do |format|
      if @activite.save
        format.html { redirect_to back_activites_path(@activite.id), notice: "Opération réussie" }
        format.json { render :show, status: :created, location: @activite }
      else
        puts ("Unable to create activite => #{@activite}, #{@activite.errors.full_messages}")
        format.html { render :new }
        format.json { render json: @activite.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @activite.update(activite_params)
        format.html { redirect_to back_activites_path(get_params), notice: "Opération réussie" }
        format.json { render :show, status: :ok, location: @activite }
      else
        puts ("Unable to update activite => #{@activite}, #{@activite.errors.full_messages}")
        format.html { render :edit }
        format.json { render json: @activite.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @activite.destroy
      respond_to do |format|
        format.html { redirect_to back_activites_path(get_params), notice: "Opération réussie" }
        format.json { head :no_content }
      end
    else
      puts ("Unable to destroy activite => #{@activite}, #{@activite.errors.full_messages}")
      redirect_to back_activites_path(get_params), alert: "Echec de l'opération"
    end
  end

  def publish_status
    if @activite.publishing(params[:publish].to_boolean)
      redirect_to back_activites_path(get_params), notice: "Opération réussie"
    else
      puts ("Unable to publish_status activite => #{@activite}, #{@activite.errors.full_messages}")
      redirect_to back_activites_path(get_params), alert: "Echec de l'opération"
    end
  end

  def update_all
    update_list_object(Activite, back_activites_path(get_params))
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_activite
    @activite = Activite.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def activite_params
    params.require(:activite).permit!
  end

  def get_params
    params.slice(:scope_published, :scope_activite_id, :scope_text)
  end

end

app/controllers/back/news_controller.rb
# -*- coding: utf-8 -*-

class Back::NewsController < BackController
  include Tools

  before_action :set_new, only: [:show, :edit, :update, :destroy, :publish_status, :previsu]

  def index
    @news = New.order("news.created_at DESC").filter(get_params).page(params[:page]).per(5)
  end

  def show
  end

  def new
    @new = New.new
  end

  def edit
  end

  def previsu
  end

  def create
    @new = New.new(new_params)

    respond_to do |format|
      if @new.save
        format.html { redirect_to back_news_index_path(@new.id), notice: "Opération réussie" }
        format.json { render :show, status: :created, location: @new }
      else
        puts ("Unable to create new => #{@new}, #{@new.errors.full_messages}")
        format.html { render :new }
        format.json { render json: @new.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @new.update(new_params)
        format.html { redirect_to back_news_index_path(get_params), notice: "Opération réussie" }
        format.json { render :show, status: :ok, location: @new }
      else
        puts ("Unable to update new => #{@new}, #{@new.errors.full_messages}")
        format.html { render :edit }
        format.json { render json: @new.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @new.destroy
      respond_to do |format|
        format.html { redirect_to back_news_index_path(get_params), notice: "Opération réussie" }
        format.json { head :no_content }
      end
    else
      puts ("Unable to destroy new => #{@new}, #{@new.errors.full_messages}")
      redirect_to back_news_index_path(get_params), alert: "Echec de l'opération"
    end
  end

  def publish_status
    if @new.publishing(params[:publish].to_boolean)
      redirect_to back_news_index_path(get_params), notice: "Opération réussie"
    else
      puts ("Unable to publish_status new => #{@new}, #{@new.errors.full_messages}")
      redirect_to back_news_index_path(get_params), alert: "Echec de l'opération"
    end
  end

  def update_all
    update_list_object(New, back_news_index_path(get_params))
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_new
    @new = New.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def new_params
    params.require(:new).permit!
  end

  def get_params
    params.slice(:scope_published, :scope_new_id, :scope_text)
  end

end

app/controllers/back/sousactivite_images_controller.rb
# -*- coding: utf-8 -*-

class Back::SousactiviteImagesController < BackController

  before_action :load_sousactivite, except: [:update_row_order]
  before_action :load_sousactivite_image, only: [:edit, :update, :destroy, :update_row_order]

  def new
    @sousactivite_image = @sousactivite.sousactivite_images.build
  end

  def create
    @sousactivite_image = SousactiviteImage.new(sousactivite_image_params)

    # To keep the mails tabs
    session[:tabs] = "#image"

    respond_to do |format|
      if @sousactivite_image.save
        format.html { redirect_to edit_back_sousactivite_path(@sousactivite.id), notice: "Mise à jour effectuée" }
      else
        format.html { redirect_to edit_back_sousactivite_path(@sousactivite.id), alert: "Echec ! <br/>#{@sousactivite_image.errors.full_messages.join(',')}" }
      end
    end
  end

  def edit
  end

  def update
    # To keep the mails tabs
    session[:tabs] = "#image"

    respond_to do |format|
      if @sousactivite_image.update_attributes(sousactivite_image_params)
        format.html { redirect_to edit_back_sousactivite_path(@sousactivite.id), notice: "Mise à jour effectuée" }
      else
        format.html { redirect_to edit_back_sousactivite_path(@sousactivite.id), alert: "Echec ! <br/>#{@sousactivite_image.errors.full_messages.join(',')}" }
      end
    end
  end

  def destroy
    session[:tabs] = "#image"
    @sousactivite_image.destroy
    redirect_to edit_back_sousactivite_path(@sousactivite.id), notice: "Mise à jour effectuée"
  end

  def update_row_order
    @sousactivite_image.update_attribute :row_order_position, params[:row_order_position]
    @sousactivite_image.save!

    render nothing: true
  end

  private

  def load_sousactivite
    @sousactivite = Sousactivite.find(params[:sousactivite_id])
  end

  def load_sousactivite_image
    @sousactivite_image = SousactiviteImage.find(params[:id])
  end

  def sousactivite_image_params
    params.require(:sousactivite_image).permit!
  end

end

app/controllers/back/sousactivites_controller.rb
# -*- coding: utf-8 -*-

class Back::SousactivitesController < BackController
  include Tools

  before_action :set_sousactivite, only: [:show, :edit, :update, :destroy, :publish_status, :previsu]

  def show
  end

  def new
    @sousactivite = Sousactivite.new
    @sousactivite.activite_id = params[:activite_id]
  end

  def edit
    @sousactivite_images = @sousactivite.sousactivite_images.rank(:row_order)
    session[:tabs] = "#text" if session[:tabs].blank?
  end

  def previsu
  end

  def create
    @sousactivite = Sousactivite.new(sousactivite_params)

    respond_to do |format|
      if @sousactivite.save
        format.html { redirect_to back_activites_path(get_params), notice: "Opération réussie" }
        format.json { render :show, status: :created, location: @sousactivite }
      else
        puts ("Unable to create sousactivite => #{@sousactivite}, #{@sousactivite.errors.full_messages}")
        format.html { render :new }
        format.json { render json: @sousactivite.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      # Then, delete images that are deleted
      @sousactivite.sousactivite_images.each do |sousactivite_image|
        if params['list_images']
          unless params['list_images'].include? sousactivite_image.id.to_s
            puts "destroy #{sousactivite_image.id}"
            sousactivite_image.destroy
          end
        end
      end
      if params['sousactivite']['sousactivite_images_attributes']
        ssact = params['sousactivite']['sousactivite_images_attributes']
        if ssact.values.last['image'].blank?
          ssact.delete(ssact.keys.last)
          params['sousactivite']['sousactivite_images_attributes'] = ssact
        end
      end
      if @sousactivite.update(sousactivite_params)
        format.html { redirect_to back_activites_path(get_params), notice: "Opération réussie" }
        format.json { render :show, status: :ok, location: @sousactivite }
      else
        puts ("Unable to update sousactivite => #{@sousactivite}, #{@sousactivite.errors.full_messages}")
        format.html { render :edit }
        format.json { render json: @sousactivite.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @sousactivite.destroy
      respond_to do |format|
        format.html { redirect_to back_activites_path(get_params), notice: "Opération réussie" }
        format.json { head :no_content }
      end
    else
      puts ("Unable to destroy sousactivite => #{@sousactivite}, #{@sousactivite.errors.full_messages}")
      redirect_to back_activites_path(get_params), alert: "Echec de l'opération"
    end
  end

  def publish_status
    if @sousactivite.publishing(params[:publish].to_boolean)
      redirect_to back_activites_path(get_params), notice: "Opération réussie"
    else
      puts ("Unable to publish_status sousactivite => #{@sousactivite}, #{@sousactivite.errors.full_messages}")
      redirect_to back_activites_path(get_params), alert: "Echec de l'opération"
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_sousactivite
    @sousactivite = Sousactivite.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sousactivite_params
    params.require(:sousactivite).permit!
  end

  def get_params
    params.slice(:scope_published, :scope_activite_id, :scope_text)
  end

end

app/controllers/back_controller.rb
# encoding: utf-8

class BackController < ApplicationController
  layout 'back'

  before_filter :authenticate_user!

end

app/views/back/sousactivite_images/_form.html.erb
<p id="popup-error-message" class="alert alert-danger" style="display:none;"></p>

<%= form_for(@sousactivite_image, :url => (@sousactivite_image.persisted? ? back_sousactivite_sousactivite_image_path(@sousactivite.id, @sousactivite_image.id) : back_sousactivite_sousactivite_images_path(@sousactivite.id))) do |sousactivite_image_form| %>

<%= sousactivite_image_form.hidden_field :sousactivite_id, :value => @sousactivite.id %>

<div class="row">
  <div class="span2">
    <div class="control-group event-table-elem-small">
      Image
    </div>
    <div class="control-group event-table-elem-small" style="padding-top: 30px;">
      Description
    </div>
  </div>
  <div class="span4">
    <div class="control-group event-table-elem-small">
      <%= sousactivite_image_form.text_field :image, :style => "width: 350px;" %>
    </div>
    <div class="control-group event-table-elem-small">
      <%= sousactivite_image_form.text_area :description, :style => "width: 350px;" %>
    </div>
  </div>
</div>

<div class="form-actions">
  <a class="btn-end btn btn-primary">Valider</a>
  <a class="close-popup-link btn btn-inverse">Fermer</a>
</div>

<% end %>

<script type="text/javascript">
var sousactivite_image_ready = function() {


  // Fields in error
  var fields_in_error = new Array();

  // Init the error messages
  function init_error(){
    $('#popup-error-message').hide();
    fields_in_error.forEach(function(field) {
      $(field).parent().removeClass('error');
    });
    fields_in_error = new Array();
  }

  // Show list of errors
  // If exists => return true
  // If no error => return false
  function is_error(message){
    message = typeof message !== 'undefined' ? message : "Champ requis";

    if (fields_in_error.length == 0) return false;
    fields_in_error.forEach(function(field) {
      $(field).parent().addClass('error');
    });
    $('#popup-error-message').text(message);
    $('#popup-error-message').show();

    return true;
  }


  // Validation of form
  function check_form(){
    if ($('#sousactivite_image_image').val() == '') fields_in_error.push('#sousactivite_image_image');
    // Submit form if no error
    return !is_error();
  }

  $('.btn-end').on('click', function(){
    init_error();
    if (check_form()) $(this).closest("form").submit();
  });
};
$(document).ready(sousactivite_image_ready);
$(document).on('page:load', sousactivite_image_ready);
</script>

app/views/back/sousactivite_images/_sousactivite_image.html.erb
<tr data-item-id=<%= "#{sousactivite_image.id}" %> class="item">
  <td class="reorder" style="cursor: move">
	  <i class="icon-ellipsis-vertical"></i>
	</td>
  <td>
    <img src="<%=sousactivite_image.image%>">
  </td>
  <td>
    <%= sousactivite_image.description %>
  </td>
  <td>
    <div class="btn-group pull-right">
      <%= link_to edit_back_sousactivite_sousactivite_image_path(@sousactivite.id, sousactivite_image.id), :remote => true, :class => 'btn btn-small static-popup-link my-tooltip', :data => { :delay => 500, :title => "Editer"} do %>
        <i class="icon-pencil"></i>
      <% end %>
      <%= link_to back_sousactivite_sousactivite_image_path(@sousactivite.id, sousactivite_image.id), :method => 'delete', :data => { :confirm => "Sûr ?", :delay => 500, :title => "Supprimer"}, :class => 'btn btn-small btn-danger my-tooltip' do %>
        <i class="icon-trash icon-white"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/back/sousactivite_images/edit.html.erb
<%= render :partial => "form", :locals => { :title => 'Mise a jour' } %>

app/views/back/sousactivite_images/edit.js.erb
$("#myModal").html("<%= j render 'form', :title =>  'Mise a jour' %>");

app/views/back/sousactivite_images/new.html.erb
<%= render :partial => "form", :locals => { :title => 'Nouveau' } %>

app/views/back/sousactivite_images/new.js.erb
$("#myModal").html("<%= j render 'form', :title =>  'Nouveau' %>");