config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'sessions'}

  scope 'admin', :module => 'back', :as => 'back' do
    root to: "activites#index"

    resources :activites do
      member do
        get  'publish_status/:publish', :action => 'publish_status', :as => 'publish_status'
        get  'previsu', :action => 'previsu', :as => 'previsu'
      end
    end
    post 'activites/update/all', to: 'activites#update_all', :as => 'activite_update_all'

    resources :sousactivites do
      member do
        get  'publish_status/:publish', :action => 'publish_status', :as => 'publish_status'
        get  'previsu', :action => 'previsu', :as => 'previsu'
      end

      post 'sousactivite_images/update_row_order', to: 'sousactivite_images#update_row_order', as: 'update_row_order', on: :collection
      resources :sousactivite_images
    end

    resources :news do
      member do
        get  'publish_status/:publish', :action => 'publish_status', :as => 'publish_status'
        get  'previsu', :action => 'previsu', :as => 'previsu'
      end
    end
    post 'news/update/all', to: 'news#update_all', :as => 'news_update_all'

  end

  scope :module => 'front', :as => 'front' do
    root :to => 'indexs#index'

    resources :contact_forms, :only => [:create]

  end

 end

app/models/activite.rb
class Activite < ActiveRecord::Base
  include Filterable
  extend FriendlyId
  friendly_id :slug_candidates, :use => :slugged

  has_many :sousactivites, :dependent => :destroy

  # Validations
  validates :title, :presence => true

  # Scopes
  scope :scope_published, -> (status) { where publish: status }
  scope :scope_activite_id, -> (activite_id) { where id: activite_id }
  scope :scope_text, -> (term) {
        word_sql = "%#{term}%"
        self.where('lower(activites.title) LIKE ?', word_sql)
  }

  def slug_candidates
    [
      :title
    ]
  end

  def all_images
    list_image = []
    sousactivites.each do |sousactivite|
      sousactivite.sousactivite_images.each do |sousactivite_image|
        list_image << sousactivite_image.image
      end
    end
    return list_image
  end

  def publishing(publish_action = true)
    sousactivites.each { |a| a.publishing(publish_action) }
    return update_attributes({:publish => publish_action})
  end

end

app/controllers/back/activites_controller.rb
# -*- coding: utf-8 -*-

class Back::ActivitesController < BackController
  include Tools

  before_action :set_activite, only: [:show, :edit, :update, :destroy, :publish_status, :previsu]

  def index
    @activites = Activite.order("activites.title ASC").filter(get_params).page(params[:page]).per(5)
    session[:tabs] = ""
  end

  def show
  end

  def new
    @activite = Activite.new
  end

  def edit
  end

  def previsu
  end

  def create
    @activite = Activite.new(activite_params)

    respond_to do |format|
      if @activite.save
        format.html { redirect_to back_activites_path(@activite.id), notice: "Opération réussie" }
        format.json { render :show, status: :created, location: @activite }
      else
        puts ("Unable to create activite => #{@activite}, #{@activite.errors.full_messages}")
        format.html { render :new }
        format.json { render json: @activite.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @activite.update(activite_params)
        format.html { redirect_to back_activites_path(get_params), notice: "Opération réussie" }
        format.json { render :show, status: :ok, location: @activite }
      else
        puts ("Unable to update activite => #{@activite}, #{@activite.errors.full_messages}")
        format.html { render :edit }
        format.json { render json: @activite.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @activite.destroy
      respond_to do |format|
        format.html { redirect_to back_activites_path(get_params), notice: "Opération réussie" }
        format.json { head :no_content }
      end
    else
      puts ("Unable to destroy activite => #{@activite}, #{@activite.errors.full_messages}")
      redirect_to back_activites_path(get_params), alert: "Echec de l'opération"
    end
  end

  def publish_status
    if @activite.publishing(params[:publish].to_boolean)
      redirect_to back_activites_path(get_params), notice: "Opération réussie"
    else
      puts ("Unable to publish_status activite => #{@activite}, #{@activite.errors.full_messages}")
      redirect_to back_activites_path(get_params), alert: "Echec de l'opération"
    end
  end

  def update_all
    update_list_object(Activite, back_activites_path(get_params))
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_activite
    @activite = Activite.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def activite_params
    params.require(:activite).permit!
  end

  def get_params
    params.slice(:scope_published, :scope_activite_id, :scope_text)
  end

end

app/controllers/back/news_controller.rb
# -*- coding: utf-8 -*-

class Back::NewsController < BackController
  include Tools

  before_action :set_new, only: [:show, :edit, :update, :destroy, :publish_status, :previsu]

  def index
    @news = New.order("news.created_at DESC").filter(get_params).page(params[:page]).per(5)
  end

  def show
  end

  def new
    @new = New.new
  end

  def edit
  end

  def previsu
  end

  def create
    @new = New.new(new_params)

    respond_to do |format|
      if @new.save
        format.html { redirect_to back_news_index_path(@new.id), notice: "Opération réussie" }
        format.json { render :show, status: :created, location: @new }
      else
        puts ("Unable to create new => #{@new}, #{@new.errors.full_messages}")
        format.html { render :new }
        format.json { render json: @new.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @new.update(new_params)
        format.html { redirect_to back_news_index_path(get_params), notice: "Opération réussie" }
        format.json { render :show, status: :ok, location: @new }
      else
        puts ("Unable to update new => #{@new}, #{@new.errors.full_messages}")
        format.html { render :edit }
        format.json { render json: @new.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @new.destroy
      respond_to do |format|
        format.html { redirect_to back_news_index_path(get_params), notice: "Opération réussie" }
        format.json { head :no_content }
      end
    else
      puts ("Unable to destroy new => #{@new}, #{@new.errors.full_messages}")
      redirect_to back_news_index_path(get_params), alert: "Echec de l'opération"
    end
  end

  def publish_status
    if @new.publishing(params[:publish].to_boolean)
      redirect_to back_news_index_path(get_params), notice: "Opération réussie"
    else
      puts ("Unable to publish_status new => #{@new}, #{@new.errors.full_messages}")
      redirect_to back_news_index_path(get_params), alert: "Echec de l'opération"
    end
  end

  def update_all
    update_list_object(New, back_news_index_path(get_params))
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_new
    @new = New.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def new_params
    params.require(:new).permit!
  end

  def get_params
    params.slice(:scope_published, :scope_new_id, :scope_text)
  end

end

app/controllers/back/sousactivite_images_controller.rb
# -*- coding: utf-8 -*-

class Back::SousactiviteImagesController < BackController

  before_action :load_sousactivite, except: [:update_row_order]
  before_action :load_sousactivite_image, only: [:edit, :update, :destroy, :update_row_order]

  def new
    @sousactivite_image = @sousactivite.sousactivite_images.build
  end

  def create
    @sousactivite_image = SousactiviteImage.new(sousactivite_image_params)

    # To keep the mails tabs
    session[:tabs] = "#image"

    respond_to do |format|
      if @sousactivite_image.save
        format.html { redirect_to edit_back_sousactivite_path(@sousactivite.id), notice: "Mise à jour effectuée" }
      else
        format.html { redirect_to edit_back_sousactivite_path(@sousactivite.id), alert: "Echec ! <br/>#{@sousactivite_image.errors.full_messages.join(',')}" }
      end
    end
  end

  def edit
  end

  def update
    # To keep the mails tabs
    session[:tabs] = "#image"

    respond_to do |format|
      if @sousactivite_image.update_attributes(sousactivite_image_params)
        format.html { redirect_to edit_back_sousactivite_path(@sousactivite.id), notice: "Mise à jour effectuée" }
      else
        format.html { redirect_to edit_back_sousactivite_path(@sousactivite.id), alert: "Echec ! <br/>#{@sousactivite_image.errors.full_messages.join(',')}" }
      end
    end
  end

  def destroy
    session[:tabs] = "#image"
    @sousactivite_image.destroy
    redirect_to edit_back_sousactivite_path(@sousactivite.id), notice: "Mise à jour effectuée"
  end

  def update_row_order
    @sousactivite_image.update_attribute :row_order_position, params[:row_order_position]
    @sousactivite_image.save!

    render nothing: true
  end

  private

  def load_sousactivite
    @sousactivite = Sousactivite.find(params[:sousactivite_id])
  end

  def load_sousactivite_image
    @sousactivite_image = SousactiviteImage.find(params[:id])
  end

  def sousactivite_image_params
    params.require(:sousactivite_image).permit!
  end

end

app/controllers/back/sousactivites_controller.rb
# -*- coding: utf-8 -*-

class Back::SousactivitesController < BackController
  include Tools

  before_action :set_sousactivite, only: [:show, :edit, :update, :destroy, :publish_status, :previsu]

  def show
  end

  def new
    @sousactivite = Sousactivite.new
    @sousactivite.activite_id = params[:activite_id]
  end

  def edit
    @sousactivite_images = @sousactivite.sousactivite_images.rank(:row_order)
    session[:tabs] = "#text" if session[:tabs].blank?
  end

  def previsu
  end

  def create
    @sousactivite = Sousactivite.new(sousactivite_params)

    respond_to do |format|
      if @sousactivite.save
        format.html { redirect_to back_activites_path(get_params), notice: "Opération réussie" }
        format.json { render :show, status: :created, location: @sousactivite }
      else
        puts ("Unable to create sousactivite => #{@sousactivite}, #{@sousactivite.errors.full_messages}")
        format.html { render :new }
        format.json { render json: @sousactivite.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      # Then, delete images that are deleted
      @sousactivite.sousactivite_images.each do |sousactivite_image|
        if params['list_images']
          unless params['list_images'].include? sousactivite_image.id.to_s
            puts "destroy #{sousactivite_image.id}"
            sousactivite_image.destroy
          end
        end
      end
      if params['sousactivite']['sousactivite_images_attributes']
        ssact = params['sousactivite']['sousactivite_images_attributes']
        if ssact.values.last['image'].blank?
          ssact.delete(ssact.keys.last)
          params['sousactivite']['sousactivite_images_attributes'] = ssact
        end
      end
      if @sousactivite.update(sousactivite_params)
        format.html { redirect_to back_activites_path(get_params), notice: "Opération réussie" }
        format.json { render :show, status: :ok, location: @sousactivite }
      else
        puts ("Unable to update sousactivite => #{@sousactivite}, #{@sousactivite.errors.full_messages}")
        format.html { render :edit }
        format.json { render json: @sousactivite.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @sousactivite.destroy
      respond_to do |format|
        format.html { redirect_to back_activites_path(get_params), notice: "Opération réussie" }
        format.json { head :no_content }
      end
    else
      puts ("Unable to destroy sousactivite => #{@sousactivite}, #{@sousactivite.errors.full_messages}")
      redirect_to back_activites_path(get_params), alert: "Echec de l'opération"
    end
  end

  def publish_status
    if @sousactivite.publishing(params[:publish].to_boolean)
      redirect_to back_activites_path(get_params), notice: "Opération réussie"
    else
      puts ("Unable to publish_status sousactivite => #{@sousactivite}, #{@sousactivite.errors.full_messages}")
      redirect_to back_activites_path(get_params), alert: "Echec de l'opération"
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_sousactivite
    @sousactivite = Sousactivite.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sousactivite_params
    params.require(:sousactivite).permit!
  end

  def get_params
    params.slice(:scope_published, :scope_activite_id, :scope_text)
  end

end

app/controllers/back_controller.rb
# encoding: utf-8

class BackController < ApplicationController
  layout 'back'

  before_filter :authenticate_user!

end

app/views/back/activites/_activite.html.erb
<tr>
  <td>
    <%= check_box('list_id', 'id', {:class => "list_id_id", :multiple => true}, activite.id, nil)%>
  </td>
  <td>
    <%= activite.title %>
  </td>
  <td><%= render :partial => "shared/boolean_icon", :locals => {:boolean => activite.publish} %></td>
  <td>
    <div class='pull-right btn-group'>
      <%= link_to edit_back_activite_path(activite.id, params.slice(:scope_text, :scope_published, :scope_activite_id)), :remote => true, :class => 'static-popup-link btn btn-small my-tooltip', :data => { :delay => 500, :title => "Editer" } do %>
        <i class="icon-pencil"></i>
      <% end %>
      <%= link_to new_back_sousactivite_path(:activite_id => activite.id), :remote => true, :class => 'btn btn-small static-popup-link my-tooltip', :data => { :delay => 500, :title => "Créer une sous-activité"} do %>
        <i class="icon-plus"></i>
      <% end %>
      <% if activite.publish? %>
        <%= link_to publish_status_back_activite_path(activite.id, 'false', params.slice(:scope_text, :scope_published, :scope_activite_id)), :class => 'btn btn-small my-tooltip btn-warning', :data => { :delay => 500, :title => "Dépublier" } do %>
          <i class="icon-remove"></i>
        <% end %>
      <% else %>
        <%= link_to publish_status_back_activite_path(activite.id, 'true', params.slice(:scope_text, :scope_published, :scope_activite_id)), :class => 'btn btn-small my-tooltip btn-warning', :data => { :delay => 500, :title => "Publier" } do %>
          <i class="icon-ok"></i>
        <% end %>
      <% end %>
      <%= link_to back_activite_path(activite.id, params.slice(:scope_text, :scope_published, :scope_activite_id)), method: :delete, data: { confirm: "Sûr ?", :delay => 500, :title => "Supprimer" }, :class => "btn btn-small my-tooltip btn-danger" do %>
        <i class="icon-trash icon-white"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/back/activites/_form.html.erb
<p id="error-message" class="alert alert-danger" style="display:none;"></p>

<%= form_for(@activite, url: @activite.persisted? ? back_activite_path(@activite.id) : back_activites_path, html: { class: "form"}) do |f| %>

<div class="row">
  <div class="span1">
    <div class="control-group" style="height:60px;padding-top:5px;">
      Nom
    </div>
  </div>
  <div class="span2">
    <div class="control-group" style='height:60px;'>
      <%= f.text_field :title, :style => "width:300px;" %>
    </div>
  </div>
</div>

<div class="form-actions">
  <a class="btn-end btn btn-primary">Valider</a>
  <a class="close-popup-link btn btn-inverse">Fermer</a>
</div>

<% end %>

<script type="text/javascript">
var activite_ready = function() {
  // Fields in error
  var fields_in_error = new Array();

  // Init the error messages
  function init_error(){
    $('#error-message').hide();
    fields_in_error.forEach(function(field) {
      $(field).parent().removeClass('error');
    });
    fields_in_error = new Array();
  }

  // Show list of errors
  // If exists => return true
  // If no error => return false
  function is_error(message){
    message = typeof message !== 'undefined' ? message : "Champs requis";

    if (fields_in_error.length == 0) return false;
    fields_in_error.forEach(function(field) {
      $(field).parent().addClass('error');
    });
    $('#error-message').text(message);
    $('#error-message').show();

    return true;
  }

  // Validation of form
  function check_form(){
    if ($('#activite_title').val() == '') fields_in_error.push('#activite_title');

    // Submit form if no error
    return !is_error();
  }

  $('.btn-end').on('click', function(){
    init_error();
    if (check_form()) $( ".form" ).submit();
  });

};
$(document).ready(activite_ready);
$(document).on('page:load', activite_ready);
</script>

app/views/back/activites/_sousactivites.html.erb
<tr>
  <td>
    <%= check_box('list_id', 'id', {:class => "list_id_id", :multiple => true}, "sa" + sousactivite.id.to_s, nil)%>
  </td>
  <td>
    <i class="icon-chevron-right"></i>
    <%= sousactivite.title %>
  </td>
  <td><%= render :partial => "shared/boolean_icon", :locals => {:boolean => sousactivite.publish} %></td>
  <td>
    <div class='pull-right btn-group'>
      <%= link_to edit_back_sousactivite_path(sousactivite.id, params.slice(:scope_text, :scope_published, :scope_activite_id)), :class => 'btn btn-small my-tooltip', :data => { :delay => 500, :title => "Editer" } do %>
        <i class="icon-pencil"></i>
      <% end %>
      <% if sousactivite.publish? %>
        <%= link_to publish_status_back_sousactivite_path(sousactivite.id, 'false', params.slice(:scope_text, :scope_published, :scope_activite_id)), :class => 'btn btn-small my-tooltip btn-warning', :data => { :delay => 500, :title => "Dépublier" } do %>
          <i class="icon-remove"></i>
        <% end %>
      <% else %>
        <%= link_to publish_status_back_sousactivite_path(sousactivite.id, 'true', params.slice(:scope_text, :scope_published, :scope_activite_id)), :class => 'btn btn-small my-tooltip btn-warning', :data => { :delay => 500, :title => "Publier" } do %>
          <i class="icon-ok"></i>
        <% end %>
      <% end %>
      <%= link_to back_sousactivite_path(sousactivite.id, params.slice(:scope_text, :scope_published, :scope_activite_id)), method: :delete, data: { confirm: "Sûr ?", :delay => 500, :title => "Supprimer" }, :class => "btn btn-small my-tooltip btn-danger" do %>
        <i class="icon-trash icon-white"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/back/activites/edit.js.erb
$("#myModal").html("<%= j render 'form', :title =>  'Edit' %>");

app/views/back/activites/index.html.erb
<h3>Activités</h3>

<div class="back-filter">
  <%= form_tag '', :method => :get, :id => 'form-back-filtered' do %>
    <div class="icon-search"></div>
    <div class="back-filter-item">
      <input name="scope_text" placeholder="Rechercher" type="text" value="<%= params[:scope_text] %>"></input>
    </div>
    <div class="back-filter-item">
      Publication<br/>
      <select name="scope_published">
        <option value="">Tous</option>
        <option value="1" <% if params["scope_published"] == "1" %>selected="selected"<% end %>>
          Publié
        </option>
        <option value="0" <% if params["scope_published"] == "0" %>selected="selected"<% end %>>
          Non publié
        </option>
      </select>
    </div>
    <div class="back-filter-item">
      Activite<br/>
      <select name="scope_activite_id">
        <option value="">Toutes</option>
        <% Activite.all.each do |activite| %>
          <option value="<%=activite.id %>"
            <% if params["scope_activite_id"].to_i == activite.id %>selected="selected"<% end %>>
            <%=activite.title%>
          </option>
        <% end %>
      </select>
    </div>
  <% end %>
</div>

<%= form_tag(back_activite_update_all_path, :method => :post, :id => 'form-back-list_id') do %>
  <input id="scope_text" name="scope_text" type="hidden" value="<%= params["scope_text"]%>">
  <input id="scope_published" name="scope_published" type="hidden" value="<%= params["scope_published"]%>">
  <input id="scope_activite_id" name="scope_activite_id" type="hidden" value="<%= params["scope_activite_id"]%>">

  <div class="back-button">
    <div class="back-main-checkbox">
      <%= check_box('list_id', 'check_all', {:multiple => true}, nil)%>
    </div>
    <div class="back-list-button-checkbox">
      <%= hidden_field 'list_id', 'action', :value => 'nothing' %>
      <%= link_to '#', :class => 'btn btn-small list_id_action my-tooltip btn-warning', 'data-action' => "publish", :data => { :delay => 500, :title => "Publier"} do %>
        <i class="icon-ok"></i>
      <% end %>
      <%= link_to '#', :class => 'btn btn-small list_id_action my-tooltip btn-warning', 'data-action' => "unpublish", :data => { :delay => 500, :title => "Dépublier"} do %>
        <i class="icon-remove"></i>
      <% end %>
      <%= link_to '#', data: { message: "Sûr ?", :delay => 500, :title => "Supprimer" },
      :class => "btn btn-small btn-danger list_id_action my-tooltip", 'data-action' => "delete" do %>
        <i class="icon-trash icon-white"></i>
      <% end %>
    </div>
    <div class="back-list-button-general">
      <%= link_to new_back_activite_path, :remote => true, :class => "btn btn-small static-popup-link my-tooltip", :data => { :delay => 500, :title => "Ajouter"} do%>
        <i class="icon-plus"></i>
      <% end %>
    </div>
  </div>

  <% if @activites.length > 0 %>
    <%= paginate @activites, :theme => 'back' %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="span1"></th>
          <th class="span3">Nom</th>
          <th class="span1">Publié</th>
          <th class="span2"></th>
        </tr>
      </thead>

      <tbody>
        <% @activites.each do |activite| %>
          <%= render partial: "activite", :locals => {:activite => activite} %>
          <% activite.sousactivites.order("title").each do |sousactivite| %>
            <%= render partial: "sousactivites", :locals => {:sousactivite => sousactivite} %>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= paginate @activites, :theme => 'back' %>
  <% end %>
<% end %>

<div class="modal hide fade" id="myModal" tabindex="-1" role="dialog" data-backdrop="static" style="width:600px; padding:30px">
</div>